---
- name: install new packages
  tags: pi_packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-gpiozero # not sure this is necessary if installed with pip requirements below
    - htop
    - virtualenv
    # to solve this error when sending postfix mail from raspbian : "SASL authentication failure: No worthy mechs found"
    - libsasl2-modules

- name: modify default pi password ("raspberry")
  user:
    name: pi
    password: "{{ vault_toto_pw | password_hash('sha512','myOwnSalt') }}"
    update_password: always
    shell: /bin/bash
    state: present
    # apparently not supported : no_log: true

- name: install repos for toto on pi
  tags: repos_for_toto_on_pi
  become: true
  ansible.builtin.git: repo={{ item.repo }} version=develop dest={{ item.dest }} clone=yes update=no
  with_items:
  - { repo: 'https://github.com/toto240325/frigo.git',            dest: '/home/toto/frigo' }
  - { repo: 'https://github.com/toto240325/utils.git',            dest: '/home/toto/utils' }
  register: output_git

- name: make sure .git/config is set to git@github:toto240325/<prj>.git... instead of https://github.com/toto240325/<prj>.git to allow edit and push back to git
  tags: mygit
  replace: path="{{ item }}/.git/config" regexp="https://github.com/toto240325" replace="git@github.com:toto240325"
  with_items:
  - "/home/toto/frigo"
  - "/home/toto/utils"

- name: change ownership
  tags: debug1
  file: path={{ item.path }} owner="toto" group="toto" state=directory recurse=yes
  with_items:
  - { path: "/home/toto/frigo" }
  - { path: "/home/toto/utils" }
#  register: output_chown

# - name: "install pip gpiozero"
#   tags: gpiozero
#   pip:
#     name: gpiozero
#     state: latest
#     virtualenv: /home/toto/venv/piloop
#   #when: ansible_facts["lsb"]["id"] != "Raspbian"

- name: Install requirements
  tags: piloop_req
  pip: 
    requirements: /home/toto/utils/piloop_requirements.txt
    virtualenv: /home/toto/venv/piloop
    #virtualenv_python: python3.7

- name: set the MAILTO cron variable
  community.general.cronvar:
    user: root
    name: MAILTO
    value: toto240325@gmail.com

# - name: try to force execution of piloop; doesn't seem to work 
#   tags: piloop
#   shell: "sleep 30 && python /home/toto/utils/piloop.py &"
#   # async: 99999
#   # poll: 0

# - name: "pip install packages for piloop"
#   pip:
#     name: gpiozero
#     state: latest
#     virtualenv: /home/toto/venv/piloop

- name: cron job to launch piloop under root
  tags: cron_piloop
  cron:
    user: root
    name: "piloop at reboot"
    special_time: reboot
    #minute: "*/5"
    #minute: "30"
    job: "sleep 60 && . /home/toto/venv/piloop/bin/activate && python /home/toto/utils/piloop.py  >> /home/toto/piloop.log"
  # when: ansible_facts["lsb"]["id"] != "Raspbian"

- name: cron job to reboot the pi every night
  tags: cron_nightly_reboot
  cron:
    user: root
    name: "nightly reboot"
    #special_time: reboot
    minute: "02"
    hour: "03"
    job: "sudo reboot"
    
- name: cron job to send an email after reboot
  tags: cron_email_after_reboot
  cron:
    user: root
    name: "cron_email_after_reboot"
    special_time: reboot
    #minute: "00"
    #hour: "03"
    job: 'sleep 60; echo "`hostname` rebooted 60 secs ago (`date`), sent from user `whoami`" | mail -s "`hostname` rebooted 60 secs ago" toto240325@gmail.com'
    
- name: cron job to send an email if too many under-voltages detected
  tags: cron_email_under-voltage
  cron:
    user: root
    name: "cron_email_under-voltage"
    #special_time: reboot
    minute: "05"
    #hour: "03"
    job: . /opt/utils/check_under-voltage.sh
    